
  spring:
    datasource:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/payment-db
      username : admin
      password : secret
    jpa:
      hibernate:
        ddl-auto: create-drop
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: true
      show-sql: true


    kafka:
      bootstrap-servers: localhost:9093
      producer:
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
        properties:
          spring.json.add.type.headers: false

  app:
    kafka:
      topic:
        messages: messages-topic
        dlx: messages-dlx
    outbox:
      processor:
        interval: 15000 # 15 seconds
      stuck-messages:
        interval: 300000 # 5 minutes
      cleanup:
        cron: "0 0 2 * * ?" # Every day at 2:00 AM


  server:
    port: 8080

  logging:
    level:
      com.example.messageservice: DEBUG
      org.springframework.kafka: INFO